### ISSUE TITLE
Publish without sharing a channel between threads

### ISSUE THREAD

**Issue by bliof** [gocardless/hutch#191]
Isn't there a problem with `Hutch.publish`? It should [not share the channel between threads](http://rubybunny.info/articles/concurrency.html). (e.g.  changing the `consumer_pool_size`)

How about adding a channel and exchange, that will be used for publishing, in `Thread.current`?

Disclaimer: I've never used the gem, just skipping through the code. I may be missing something.

**Comment by michaelklishin** [comment]
You are right, `Hutch.publish` does not assume concurrent publishing and it's a no-no with Bunny and pretty much every other client. Feel free to look into extending Hutch to fit into those cases but `Hutch.publish` is primarily meant to be used from Web apps which in Ruby are quite often single threaded for most intents and purposes.

**Comment by teodor-pripoae** [comment]
@michaelklishin I'm using hutch with Puma webserver and also inside sidekiq which are both multithreaded. I'm pretty sure it is a common use case.

I've been running Hutch.publish inside sidekiq for a long time and I didn't have problems. What type of problem is expected due to sharing the same connection ? As far as I know it's not possible to concurrently send Hutch.publish when running inside MRI due to the GIL.

**Comment by bliof** [comment]
@teodor-pripoae The GVL (or GIL) gives guarantees that only MRI's native C functions are atomic, not the Ruby code. Also note that you should not share the channels. You have one connection with multiple channels. I am not sure of what problems may occur. You may mix the [frames of the messages](http://rubybunny.info/articles/concurrency.html#sharing_channels_between_threads) but I don't known what will happen then (but it should be bad - maybe an error because of invalid message or maybe the messages could mix their metadata/payload (there is no mention of checksum/hash at first glance in the [spec](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)) :))

@michaelklishin I'll try to write a patch next week.

**Comment by michaelklishin** [comment]
@teodor-pripoae unfortunately the fact that you haven't run into a concurrency hazard with Hutch doesn't mean they are not possible.

The GIL prevents parallelism but not concurrency. It doesn't guarantee much w.r.t. correct frame ordering on the wire. Every `basic.publish` frame is followed by at least one, and most often two, frames:

```
[basic.publish ch=1][content header ch=1][payload chunk ch=1]*
```

with concurrent publishing on a shared channel it can become

```
[basic.publish ch=1][content header ch=1][basic.publish ch=1][payload chunk ch=1][content header ch=1][payload chunk ch=1]
```

which is a fatal protocol violation by a client as far as RabbitMQ is concerned. The right thing to do is not to share channels and not to rely on the GIL. Another reason to not rely on the GIL is that it doesn't exist on JRuby.

The right thing to do is to not share channels, and Hutch doesn't currently make that easy for those who need it. There are few reasons to not share a connection in this particular case (e.g. if one connection is blocked by a resource-driven alarm, they all will be because they all publish by definition). We need to keep the existing API backwards compatible, too.
So lets see what @bliof comes up with.

**Comment by teodor-pripoae** [comment]
Cool, thanks for the answers. How is the error treated right now ? Does it fail silently or it raises some bunny exception ?

**Comment by michaelklishin** [comment]
@teodor-pripoae like I said, it is a fatal connection-level exception. Bunny will report it as a connection closure.

**Comment by teodor-pripoae** [comment]
Ok. Thank you. It looks I didn't run into this problem yet.

**Comment by kwstannard** [comment]
@teodor-pripoae I was getting a lot of Timeout errors.

Here was my fix for the bunny/hutch concurrency issue that seems to fix the problem in production:
```ruby
  class HutchThreadsafeWrapper
    class << self
      def publish(routing_key, payload)
        connection.publish routing_key, payload
      end

      private

      def connection
        Thread.current[:hutch_connection] ||= new_connection
      end

      def new_connection
        Hutch::Broker.new(Hutch::Config).tap{|b| b.connect}
      end
    end
  end
```
Feel free to use this or warn me that this is going to blow up in my face. I am not really a threading expert.
